# default: &default
#   adapter: postgresql
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.db

development:
  adapter: postgresql
  encoding: unicode
  database: inventory_dev
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_URL'] || 'db' %>
  # database: <%= ENV['DATABASE_NAME'] || 'sinatra' %>
  # username: <%= ENV['DATABASE_USER'] || 'sinatra' %>
  # password: <%= ENV['DATABASE_PASSWORD'] || 'sinatra' %>

